$(document).ready(function(){
    $("#but1").click(function(){
        $("#panel1").toggle();
    });
    $("#but2").click(function(){
        $("#panel2").toggle();
    });
    $("#but3").click(function(){
        $("#panel3").toggle();
    });
    $("#but4").click(function(){
        $("#panel4").toggle();
    });
    $("#but5").click(function(){
        $("#panel5").toggle();
    });
});